spring:
  datasource:
    url: jdbc:h2:mem:restaurantvoting
  jpa:
    #show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        #format_sql: true
        jdbc.batch_size: 20
  # https://stackoverflow.com/a/51050702/22653131
  # Handle resource mapping errors via ControllerAdvice.
  # Otherwise, there is no exception thrown and we get standard Spring error response.
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

caching:
  lunchesTTL: 86_400_000

deadline:
  time: '12:00'
  timezone: 'Europe/Moscow'

jwt:
  secret: VUxUUkFfTUVHQV9UT1BfU0VDUkVUX0tFWV9OT09ORV9ORVZFUl9HVUVTU0VTDQo=
  lifetime: 3d

springdoc.swagger-ui.path: /swagger
