spring:
  datasource:
    url: jdbc:h2:mem:restaurantvoting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
